/*
 * This file was automatically generated by a code gen by Dmidma.
 * It helps get this done quicker.
 * You can delete it and do your own shit.
 */


import { combineReducers } from 'redux'


// import { reducerName } from './FileName'

export default combineReducers({})
